# Generated by Django 3.2.7 on 2021-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/demopic/1.jpg', null=True, upload_to='images/'),
        ),
    ]
